### ISSUE TITLE
Doesn't work with latest Raspberry Pi OS

### ISSUE THREAD

**Issue by tamerz** [corelight/raspi-corelight#4]
The Raspberry Pi Imager defaults to a newer version of the OS is that is based on Debian Bullesye instead of Buster.

Either this script should be updated (ideal scenario), or make it clear that you need to use the "Raspberry Pi OS (Legacy)" image.

**Comment by supermjr** [comment]
Just installed using the latest 64-bit image without issue.

**Comment by markoverholser** [comment]
This should have been resolved already, if you are still having issues please reach out in the CorelightCommunity Slack workspace.
